apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-udi-app"
  annotations:
    github.com/project-slug: kevariste225/my-udi-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
